config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'

  resources :events, only: [:index]
  resources :sessions, only: [:create, :destroy]
  resources :registrations, only: [:create]
  resources :checkouts, only: [:create]

  mount Admin::Engine => '/admin'
  mount Catalog::Engine => '/library'
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
  helper_method :current_user
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def create
    if current_user.present?
      redirect_to library_path,
                  notice: 'You have successfully checked out the item.'
    else
      redirect_to library_path,
                  alert: 'You must be signed in to check out an item.'
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def create
    if current_user.present?
      redirect_to events_path,
                  notice: 'You have successfully registered for the event.'
    else
      redirect_to events_path,
                  alert: 'You must be signed in to register for an event.'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:user_id] = params[:user_id]
    redirect_to root_path, notice: 'You have been logged in successfully.'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'You have been logged out successfully.'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<h1 class="title text-center"> July 2014 </h1>
<div class="calendar" data-toggle="calendar">
  <div class="row">
    <div class="col-xs-12 calendar-day calendar-no-current-month">
      <time datetime="2014-06-29">29</time>
    </div>
    <div class="col-xs-12 calendar-day calendar-no-current-month">
      <time datetime="2014-06-30">30</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-01">01</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-02">02</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-03">03</time>
      <div class="events">
        <div class="event">
          <h4>Mid Day Dance Break - SELF CARE</h4>
          <div class="desc">
            <p>Take a Break and enjoy Live dance and Art from Eries own local Talent</p>
            <p>Support for this program is provided in part from an Erie Arts & Culture Project Grant, made possible by community contributions to the Combined Arts & Cultural Campaign and the Erie Arts Endowment.</p>
          </div>
          <div class="location"> <span class="glyphicon glyphicon-map-marker"></span> State St and Rt 5, Erie, Pa.</div>
          <div class="datetime"> <span class="glyphicon glyphicon-time"></span> 12:00am - 1:00pm</div>
          <div class="attending">
            <img src="http://api.randomuser.me/portraits/women/54.jpg" />
            <img src="http://api.randomuser.me/portraits/men/27.jpg" />
            <img src="http://api.randomuser.me/portraits/men/61.jpg" />
          </div>
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="6" aria-valuemin="0" aria-valuemax="134" style="width: 4.477%;">
              <span class="sr-only">4.477% Filled</span>
            </div>
          </div>
        </div>
        <%= link_to 'Register', registrations_path, method: :post, class: 'btn btn-success' %>
      </div>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-04">04</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-05">05</time>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-06">06</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-07">07</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-08">08</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-09">09</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-10">10</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-11">11</time>
      <div class="events">
        <div class="event">
          <h4>Local artist showing, meet and greet and feature film</h4>
          <div class="desc">
            <p>We will be showing local artists films on our new 16 foot movie screen with feature film last "Carnival Of Souls", come see the new BT, hang out and socialize while enjoying some local talent. FREE event, suggested $2 or $3 donation. Concessions, popcorn, soda etc available so come hungry!!</p>
            <p>*This event is all ages welcomed and also handicapped accessible (side entrance ramp)</p>
            <p>Featuring :</p>
            <ul>
              <li><a href="https://www.youtube.com/user/walrys11/videos">Jack Rys</a></li>
              <li><a href="http://society6.com/wombglow">Alex Wilson</a></li>
              <li><a href="http://www.erieartcompany.com/">Brad Ford</a></li>
              <li><a href="http://www.youtube.com/watch?v=dkTz0EvfEiY">Carnival of Souls</a> (Trailer)</li>
            </ul>
          </div>
          <div class="location"> <span class="glyphicon glyphicon-map-marker"></span> 145 West 11th Street, Erie, Pa.</div>
          <div class="datetime"> <span class="glyphicon glyphicon-time"></span> 7:00pm - ?</div>
          <div class="attending">
            <img src="http://api.randomuser.me/portraits/women/31.jpg" />
            <img src="http://api.randomuser.me/portraits/women/47.jpg" />
            <img src="http://api.randomuser.me/portraits/women/93.jpg" />
          </div>
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="43" aria-valuemin="0" aria-valuemax="368" style="width: 11.68%;">
              <span class="sr-only">11.68% Filled</span>
            </div>
          </div>
        </div>
        <%= link_to 'Register', registrations_path, method: :post, class: 'btn btn-success' %>
      </div>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-12">12</time>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-13">13</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-14">14</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-15">15</time>
      <div class="events">
        <div class="event">
          <h4>Erie Art Museum 91st Annual Spring Show</h4>
          <div class="desc">
            <p>This juried, regional multi-media exhibition, open to all artists living within a 250-mile radius of Erie represents all media and showcases the most current and finest artwork created in the area.</p>
          </div>
          <div class="location"> <span class="glyphicon glyphicon-map-marker"></span> Presque Isle State Park </div>
          <div class="datetime"> <span class="glyphicon glyphicon-time"></span> ALL DAY</div>
          <div class="attending">
            <img src="http://api.randomuser.me/portraits/men/10.jpg" />
            <img src="http://api.randomuser.me/portraits/men/23.jpg" />
            <img src="http://api.randomuser.me/portraits/men/66.jpg" />
          </div>
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="69" aria-valuemin="0" aria-valuemax="320" style="width: 21.56%;">
              <span class="sr-only">21.56% Filled</span>
            </div>
          </div>
        </div>
        <%= link_to 'Register', registrations_path, method: :post, class: 'btn btn-success' %>
      </div>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-16">16</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-17">17</time>>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-18">18</time>
    </div>
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-19">19</time>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 calendar-day">
      <time datetime="2014-07-20">20</time>
      <div class="events">
        <div class="event">
          <h4>Mouse0270's 24th Birthday</h4>
          <div class="desc">
            <p style="text-align:center;">Friendships are one of the few things that improve with age<br/>
              The family and friends of <br/>
              Mouse0270 <br/>
              invite you to celebrate his <br/>
              24th Birthday and a lifetime of good friendship</p>
            </div>
            <div class="location"> <span class="glyphicon glyphicon-map-marker"></span> Erie, Pa </div>
            <div class="datetime"> <span class="glyphicon glyphicon-time"></span> 10:00pm - 2:00am </div>
            <div class="attending">
              <img src="https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-xfa1/t1.0-9/417157_4897339837183_626079670_n.jpg" />
            </div>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="336" style="width: 0.29%;">
                <span class="sr-only">0.29% Filled</span>
              </div>
            </div>
          </div>
        </div>
        <%= link_to 'Register', registrations_path, method: :post, class: 'btn btn-success' %>
      </div>
      <div class="col-xs-12 calendar-day">
        <time datetime="2014-07-21">21</time>
      </div>
      <div class="col-xs-12 calendar-day">
        <time datetime="2014-07-22">22</time>
      </div>
      <div class="col-xs-12 calendar-day">
        <time datetime="2014-07-23">23</time>
      </div>
      <div class="col-xs-12 calendar-day">
        <time datetime="2014-07-24">24</time>
      </div>
      <div class="col-xs-12 calendar-day">
        <time datetime="2014-07-25">25</time>
      </div>
      <div class="col-xs-12 calendar-day">
        <time datetime="2014-07-26">26</time>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 calendar-day">
        <time datetime="2014-07-27">27</time>
      </div>
      <div class="col-xs-12 calendar-day">
        <time datetime="2014-07-28">28</time>
      </div>
      <div class="col-xs-12 calendar-day">
        <time datetime="2014-07-29">29</time>
      </div>
      <div class="col-xs-12 calendar-day">
        <time datetime="2014-07-30">30</time>
      </div>
      <div class="col-xs-12 calendar-day">
        <time datetime="2014-07-31">31</time>
      </div>
      <div class="col-xs-12 calendar-day calendar-no-current-month">
        <time datetime="2014-08-01">01</time>
      </div>
      <div class="col-xs-12 calendar-day calendar-no-current-month">
        <time datetime="2014-08-02">02</time>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <hr>
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Zoolander 2016</p>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Zoolander", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Library", '/library' %></li>
        <li><%= link_to "Events", events_path %></li>
      </ul>

      <% if !current_user.present? %>
        <%= form_tag("/sessions", method: "post", class: "navbar-form navbar-right") do %>
          <div class="form-group">
            <input type="text" name="user_id" class="form-control" placeholder="User ID">
          </div>
          <%= submit_tag("Login", class: "btn btn-default") %>
        <% end %>
      <% else %>
        <%= form_tag("/sessions/#{current_user.id}", method: "delete", class: "navbar-form navbar-right") do %>
          <%= submit_tag("Logout", class: "btn btn-default") %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zoolander Admin</title>
  <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zoolander</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
    <a class="close" href="#" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  </div>
<% end %>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/index.html.erb
<!-- Image Background Page Header -->
<!-- Note: The background image is set within the business-casual.css file. -->
<header class="business-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="tagline">The Derek Zoolander Center For Kids Who Can't Read Good And Wanna Learn To Do Other Stuff Good Too</h1>
      </div>
    </div>
  </div>
</header>

<!-- Page Content -->
<div class="container">
  <hr>
  <div class="row">
    <div class="col-sm-8">
      <h2>What We Do</h2>
      <p><%= Faker::Lorem.paragraphs.join(" ") %></p>
      <p><%= Faker::Lorem.paragraphs.join(" ") %></p>
      <p>
        <%= link_to 'View Our Library &raquo;'.html_safe, '/library', class: 'btn btn-default btn-lg' %>
      </p>
    </div>
    <div class="col-sm-4">
      <h2>Contact Us</h2>
      <address>
        <strong>The Derek Zoolander Center...</strong>
        <br><%= Faker::Address.street_address %>
        <br><%= "#{Faker::Address.city}, #{Faker::Address.state_abbr} #{Faker::Address.zip}" %>
        <br>
      </address>
      <address>
        <abbr title="Phone">P:</abbr> <%= Faker::PhoneNumber.cell_phone %>
        <br>
        <abbr title="Email">E:</abbr> <a href="mailto:#"><%= Faker::Internet.email %></a>
      </address>
    </div>
  </div>
  <!-- /.row -->

  <hr>

  <div class="row">
    <div class="col-sm-4">
      <img class="img-circle img-responsive img-center" src="<%= Faker::Avatar.image %>" alt="">
      <h2><%= Faker::Lorem.words.join(" ") %></h2>
      <p><%= Faker::Lorem.paragraphs.join(" ") %></p>
    </div>
    <div class="col-sm-4">
      <img class="img-circle img-responsive img-center" src="<%= Faker::Avatar.image %>" alt="">
      <h2><%= Faker::Lorem.words.join(" ") %></h2>
      <p><%= Faker::Lorem.paragraphs.join(" ") %></p>
    </div>
    <div class="col-sm-4">
      <img class="img-circle img-responsive img-center" src="<%= Faker::Avatar.image %>" alt="">
      <h2><%= Faker::Lorem.words.join(" ") %></h2>
      <p><%= Faker::Lorem.paragraphs.join(" ") %></p>
    </div>
  </div>
  <!-- /.row -->
</div>
<!-- /.container -->